### ISSUE TITLE
Improper/missing use of modern Javascript features.

### ISSUE THREAD

**Issue by briansturgill** [jscad/OpenJSCAD.org#1051] opened 2022-04-04 18:26 UTC
## Expected Behavior
Yes.

## Actual Behavior
No.

## Steps to Reproduce the Problem

  1. Not using Set when more appropriate than Map. Note: use of Map vs Set will double memory usage.
  See hullGeom2.js, line 17 & 26, hullGeom3.js line 20 & 29.
 
  2. When using Map() with vectors or other numbers, you sometimes convert to string. This just isn't necessary, Map and Set can be indexed by any Javascript type. This is done in hullGeom2&3.js. See vertexMap and edgeCount in repairSlice.js (These should be Maps!).
  
  3. insertTjunctions.js violates everything, you misuse an object, indexed with a string and used as a set.
  It starts with "sidestocheck" at line  165. Also all use of "tags" there are unnecessary.
  
  4. Generally all Objects and Map and Set usages should be audited. Or at least put on the list of things to look out for.

## Specifications

  - Version:
  - Platform:
  - Environment: (browser, local server, node.js etc)

**Comment by platypii** [comment] 2022-04-04 19:30
> 2\. When using Map() with vectors or other numbers, you sometimes convert to string. This just isn't necessary

Disagree on this point. We are trying to find unique points by value, not by pointer. It's important that duplicate points, but with different underlying pointers, still map to the same entry. So two different points with `[1,2]` and `[1,2]` should map to the same entry, regardless of how they are created.

Not what we want:
```js
const m = new Set()
m.add([1,2])
m.add([1,2])
m.size === 2
```

This is what we want:
```js
const m = new Set()
m.add(`${[1,2]}`)
m.add(`${[1,2]}`)
m.size === 1
```

Overall great feedback though! I agree that we should audit Maps and Sets across the codebase to make sure we are using them optimally.

**Comment by briansturgill** [comment] 2022-04-04 19:47
Interesting... this is the problem with really only having book learning on the subject.
When I was translating... I had to often read the Javascript spec and it says that all types work.
Apparently they don't consider lists a type.
Note, I do this in C# all the time. For a class, you have to have IEquatable implemented.
For tuples (anonymous structs) you don't have to do anything, it just works.
I.E. You can:
Dictionary<(double, double), object>()[(1,2)] = "some stuff" and (1,2) will act exactly as you expect.
I of course implemented IEquatable on my Vec2/3 class (really all of them).

**Comment by hrgdavor** [comment] 2022-04-04 20:05
Just wondering, have not seen any articles or mentions ...

could it be that there is performance improvement if using classes Vec3 with declared x,y,z fields instead of arrays. JIT compiler is likely to have more options for optimisations. I am wondering if performance is the reasong threejs and babylonjs use classes Vec3 vec4 Color3 Color4 ...

**Comment by briansturgill** [comment] 2022-04-04 20:45
@platypii You got me curious... so C# doesn't let me do it with Arrays or Lists.
However Python does. Python is the dynamic language I use the most so is likely why I interpreted the spec to mean it work for lists too.

**Comment by z3dev** [comment] 2022-04-04 23:40
> Interesting... this is the problem with really only having book learning on the subject.
> When I was translating... I had to often read the Javascript spec and it says that all types work.
> Apparently they don't consider lists a type.
> Note, I do this in C# all the time. For a class, you have to have IEquatable implemented.
> For tuples (anonymous structs) you don't have to do anything, it just works.
> I.E. You can:
> Dictionary<(double, double), object>()[(1,2)] = "some stuff" and (1,2) will act exactly as you expect.
> I of course implemented IEquatable on my Vec2/3 class (really all of them).

SIGH. The original implementation was using Map with the vectors, but it turns out that converting to string provided a huge performance improvement. I suspect that the issue is with the comparison of objects which occurs dead last after all other types have been passed by. Anyway, we are at the mercy of the javascript engines.

**Comment by z3dev** [comment] 2022-04-04 23:43
GAGA. I hope the code isn’t using OBJECT for hashing. If so, that needs to be fixed.

**Comment by z3dev** [comment] 2022-04-09 07:45
> 4\. Generally all Objects and Map and Set usages should be audited. Or at least put on the list of things to look out for.

```
geometries/geom2/toOutlines.js:  const vertexMap = new Map()
geometries/geom3/validate.js:  const edgeCount = new Map()
operations/booleans/scissionGeom3.js:  const indexesPerPoint = new Map()
operations/expansions/expandShell.js:  const vertices2planes = new Map() // {vertex: [vertex, [plane, ...]]}
operations/expansions/expandShell.js:  const edges2planes = new Map() // {edge: [[vertex, vertex], [plane, ...]]}
operations/expansions/offsetFromPoints.js:    const pointIndex = new Map() // {point: index}
operations/hulls/hullGeom2.js:  const found = new Map()
operations/hulls/hullGeom3.js:  const found = new Map()
operations/modifiers/insertTjunctions.js:  const sidemap = new Map()
operations/modifiers/mergePolygons.js:  const edgeList = new Map()
geometries/geom2/toOutlines.js:  const vertexMap = new Map()
geometries/geom3/validate.js:  const edgeCount = new Map()
operations/booleans/scissionGeom3.js:  const indexesPerPoint = new Map()
operations/expansions/expandShell.js:  const vertices2planes = new Map() // {vertex: [vertex, [plane, ...]]}
operations/expansions/expandShell.js:  const edges2planes = new Map() // {edge: [[vertex, vertex], [plane, ...]]}
operations/expansions/offsetFromPoints.js:    const pointIndex = new Map() // {point: index}
operations/hulls/hullGeom2.js:  const found = new Map()
operations/hulls/hullGeom3.js:  const found = new Map()
operations/modifiers/insertTjunctions.js:  const sidemap = new Map()
operations/modifiers/mergePolygons.js:  const edgeList = new Map()
```

**Comment by z3dev** [comment] 2022-05-02 08:34
Closing as the use of map vs set has been reviewed. only the hull logic was adjusted.

**Comment by z3dev** [comment] 2022-05-25 07:44
Reopening as there are additional functions using... yup... objects for maps.
- DONE slice.repairSlice()
- DONE reTesselateCoplanarPolygons() in booleans

If anyone knows of more then please add a comment.

**Comment by z3dev** [comment] 2022-06-10 11:59
@platypii would you like to rework insertTjunctions() ? If not then I'll start working on the changes.

**Comment by platypii** [comment] 2022-06-12 04:07
I'll take a shot at it, unless you've already started working on it

**Comment by z3dev** [comment] 2022-06-12 05:02
Go for it.

**Comment by z3dev** [comment] 2022-06-17 02:25
I believe that all the functions are now using proper maps. Closing this issue.

**Closed by z3dev** 2022-06-17 02:25 UTC
