### ISSUE TITLE
Where did the community go? Where is it now?

### ISSUE THREAD

**Issue by The3rdIcon** [jscad/OpenJSCAD.org#442] opened 2019-04-10 16:40 UTC
With google plus shutdown, I have clue where to do to ask question. Is here the right place?

The documentation is inclear to me when it says "The CSG library functions can also be used. NOTE: Deprecated in the V2 API." Does this mean that I can only use the scripting language native to the openscad? Can someone provide clarification if this is the correct place to post this question.

**Comment by z3dev** [comment] 2019-04-10 21:41
https://openjscad.nodebb.com/categories

**Comment by z3dev** [comment] 2019-04-10 21:44
About V2... We are moving towards functions, not classes. So the CSG/CAG/etc objects will soon be gone. Of course, you can use now but later your scripts will need some changes.

**Comment by udif** [comment] 2019-05-14 19:09
I understand we can no longer cascade methods in V2, but WHY?
This is horrible.
Once I had an intuitive design process where I started with an object, then added/subtracted from it, which was directly reflected in the code.

Now I have to either:
1. Build a huge nested tree of union/difference/etc. calls, and start writing from the inside out (it's like the way you have to convert regular math equaions to RPN on HP calculators).
2. Give a temporary variable for each operation, and break it into a separate expressions.
Either way is way less elegant than what we had before.

Do we have any document outlining the goals of V2, and why are we breaking everything to achieve it?
I only see a V2 checklist, detailing the WHAT, but not the WHY!

**Comment by z3dev** [comment] 2019-05-14 22:56
@udif all good points but the goal is to correct the API, and move towards JavaScript interoperability. Having two ways of doing things (CSG Objects and OpenSCAD-like functions) just confused folks. Also, the inconsistency of names, parameters, values, etc. causes a lot of nightmares.

At the core level, everything will be functions organized in to smaller modules. We’ve been working towards this goal for a few years now, breaking the huge monolithic objects into functional pieces, and it’s time to complete this reorganization.

Above, there will be various higher level API layers. I’ve already played with several flavors. A lot more will be possible, including wrapping of the V2 functions inside of CSG/CAG objects, if someone wants to. It’s not hard.

**Comment by WolfgangFahl** [comment] 2019-06-11 16:41
At this point i am not very happy with the state of affairs.

https://stackoverflow.com/questions/56520743/integrating-openjscad-into-mediawiki/56520809#56520809

shows where the problem is.

There has been an OpenJsCad which could be integrated into web pages with just sourcing a bit of JavaScript. See http://wiki.bitplan.com/index.php/Template:Jscad. But then e.g. http://wiki.bitplan.com/index.php/UltrasonicSensorServoMount does not work since the syntax has changed (improved?) and is incompatible. There are quite a few nice examples for OpenJSCAD galleries  out there that show how to bring OpenJSCAD to life (in the social sense of exchanging JSCAD models between users) but most of them are not open source or abandoned see e.g. the examples in

 https://github.com/jscad/OpenJSCAD.org/wiki/Other-Websites-using-OpenJSCAD.org

one nice one being

http://www.z3d.jp/lab/

The current concentration on a V2 future that is on the way of cannibalizing V1 which already cannibalized a working OpenJsCad seems to be very counter productive in the social sense to me.   

How could the community grow if it is alienated this way? Personally I already spent days with little details like blockscad exports in openscad being incompatible with OpenJSCAD. There are lots of people out there using such stuff as OpenScad, Blockscad or OpenJsCAD v1. 

If you are looking for an incompatible upgrade you'll learn the same lessons IBM learned before OS/360 many years ago - people will simply go away and not bother ...

**Comment by z3dev** [comment] 2019-06-11 23:34
@WolfgangFahl Thanks for the great information but I’m sorry to say that there’s just not enough people devoted to this project. There’s really only two of us doing serious development, which is part time at best.

If we could find a sponsor then full time might be possible.

As far as integrating JSCAD into other websites, we know that there is a steep learning curve, and little documentation. There are a lot of people playing with the newer components, and that’s the focus of V2, making more easy to use building blocks. We want people to build anything.

Thanks for the compliment. The Z3D Lab is my website. 😃 

You seem to be focused on integrating JSCAD into WIKI pages. That may not be hard. If interested then let’s try. You seem to have some knowledge about what’s required.

**Comment by WolfgangFahl** [comment] 2019-06-12 17:36
https://stackoverflow.com/a/56552702/1497139 might be  a start. If things would only be documented sigh ...

**Comment by kaosat-dev** [comment] 2019-06-12 19:54
@WolfgangFahl 
- embed for V1 was merged months bacl https://github.com/jscad/OpenJSCAD.org/commit/f25d8c0b8af42e9e4fe9b8b626bc39afa9bbaf15
- for V2 you can literally use the same code & includes as here https://github.com/jscad/OpenJSCAD.org/blob/V2/packages/web/demo.html

**Comment by WolfgangFahl** [comment] 2019-06-16 06:43
@kaosat-dev thank you for this hint - i added the link to the stackoverflow question. I'll now open a separate issue for the MediaWiki integration

**Closed** 2019-07-28 08:40 UTC
