### ISSUE TITLE
OpenJSCAD cli error when converting DXF

### ISSUE THREAD

**Issue by BGEray** [jscad/OpenJSCAD.org#395] opened 2018-08-12 05:47 UTC
## Expected Behavior
convert dxf to svg

## Actual Behavior
an error occured, convert failed.

## Steps to Reproduce the Problem

  1.npm install -g @jscad/cli
  2.openjscad newCAD.dxf -of svg
Error message is:
converting newCAD.dxf -> newCAD.svg (Scalable Vector Graphics Format)
TypeError: cag._toCSGWall is not a function
    at /usr/local/lib/node_modules/@jscad/cli/node_modules/@jscad/csg/src/core/CAG.js:43:26
    at Array.map (<anonymous>)
    at CAG.union (/usr/local/lib/node_modules/@jscad/cli/node_modules/@jscad/csg/src/core/CAG.js:42:18)
    at mergeSolids2 (/usr/local/lib/node_modules/@jscad/cli/node_modules/@jscad/core/utils/mergeSolids.js:71:21)
    at prepareOutput (/usr/local/lib/node_modules/@jscad/cli/node_modules/@jscad/core/io/prepareOutput.js:20:14)
    at /usr/local/lib/node_modules/@jscad/cli/generateOutputData.js:116:28
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)

## Specifications

  - Version:
openjscad -v
OpenJSCAD 1.8.4 [Linux:4.15.0-30-generic,linux:x64]
OpenSCAD Compatibility (1.8.4)
/usr/local/lib/node_modules/@jscad/cli/cli.js:178
      outputFile = outputFile.replace(/\.([^\.]+)$/, '.' + ext) // compose output filename
                              ^

TypeError: Cannot read property 'replace' of undefined
    at determineOutputNameAndFormat (/usr/local/lib/node_modules/@jscad/cli/cli.js:178:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/@jscad/cli/cli.js:55:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  - Platform:Ubuntu 16.04.3 LTS
  - Environment: (browser, local server, node.js etc)
node --version v8.9.3

**Comment by BGEray** [comment] 2018-08-13 06:53
Hi, @z3dev ,supply a file name cause the same error:
openjscad newCAD.dxf -of svg -o test.svg
converting newCAD.dxf -> test.svg (Scalable Vector Graphics Format)
TypeError: cag._toCSGWall is not a function
    at /usr/local/lib/node_modules/@jscad/cli/node_modules/@jscad/csg/src/core/CAG.js:43:26
    at Array.map (<anonymous>)
    at CAG.union (/usr/local/lib/node_modules/@jscad/cli/node_modules/@jscad/csg/src/core/CAG.js:42:18)
    at mergeSolids2 (/usr/local/lib/node_modules/@jscad/cli/node_modules/@jscad/core/utils/mergeSolids.js:71:21)
    at prepareOutput (/usr/local/lib/node_modules/@jscad/cli/node_modules/@jscad/core/io/prepareOutput.js:20:14)
    at /usr/local/lib/node_modules/@jscad/cli/generateOutputData.js:116:28
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)

**Comment by z3dev** [comment] 2020-02-24 03:48
@BGEray V2 has improved conversation of DXF files. If you can attach a sample DXF file here (use the .txt extension) then I could try.

**Comment by danielmaartens** [comment] 2020-07-06 08:56
@Spiritdude @kaosat-dev 

@BGEray I'm also running into the same ```cag._toCSGWall is not a function``` error when trying to convert .jscad to .svg using this command:
``openjscad example001.jscad -of svg -o test.svg```

@z3dev 
Did you get anywhere with this ?

What is the cause of this ? Do I need to do anything else to get this to work ?

**Comment by z3dev** [comment] 2020-07-06 11:28
I suspect that there are LINE entities in the DXF file. Those cannot be converted using V1 CLI.

**Comment by z3dev** [comment] 2020-08-04 05:37
@danielmaartens @BGEray here's some information which may help.

V1 is not very flexible when exporting. The objects being exported must match the format, i.e. 2D objects exported to 2D formats, 3D objects exported to 3D formats.
```
node ./cli.js 3d.js -of stl
converting 3d.js -> 3d.stl (STereoLithography, Binary)
node ./cli.js 2d.js -of svg
converting 2d.js -> 2d.svg (Scalable Vector Graphics Format)
```
If you mess up and try to export incompatible objects then BIG time errors are throw.

**Comment by z3dev** [comment] 2020-10-23 06:22
@danielmaartens @BGEray please try this with V2 JSCAD cli command. here's how to get started...

https://openjscad.org/dokuwiki/doku.php?id=early_v2

**Comment by z3dev** [comment] 2021-04-30 06:28
@danielmaartens @BGEray please try again with V2+ of the CLI. (or website openjscad.xyz)

I think the results will be better. I will close this issue if there's not response in 1 month.

**Comment by z3dev** [comment] 2021-10-03 06:23
Closing as no example DXF file was supplied for testing.

**Closed by z3dev** 2021-10-03 06:23 UTC
Labels: data export, command line app
