### ISSUE TITLE
CSG.ConnectorList does not work in current code on github

### ISSUE THREAD

**Issue by cbrunschen** [jscad/OpenJSCAD.org#299] opened 2017-10-16 18:42 UTC
See discussion on https://plus.google.com/+ChristianBrunschen/posts/JYdwR99GQTH

I'm trying to use CSG.ConnectorList but having mixed success. A simple example like 

function main() {
  var cs = new CSG.ConnectorList();
  cs.appendConnector(
      new CSG.Connector([0,0,0], [0,0,1], [1,0,0]));
  cs.appendConnector(
      new CSG.Connector([0,0,12], [0,0,1], [1,0,0]))
  return cs.followWith(CAG.circle({center:[0,0], radius:5,}));
}

works fine when entered into https://openjscad.org/ , but when I run OpenJSCAD locally, I get "TypeError: CSG.ConnectorList is not a constructor" .

I just did a fresh sequence of:

git clone github.com - jscad/OpenJSCAD.org
cd OpenJSCAD.org
python -m SimpleHTTPServer 8001

pointed a web browser (Google Chrome, version Version 61.0.3163.100)  at 

http://localhost:8001/

which reports version "1.0.3"; I pasted in the code above and reproduced the error, "TypeError: CSG.ConnectorList is not a  constructor".

I also pointed the same browser at https://openjscad.org/ which reports version "OpenJSCAD.org 1.0.1", pasted the exact same code, and there is worked.

I took screenshots of each: https://imgur.com/a/gBJr7

**Comment by kaosat-dev** [comment] 2017-10-17 21:18
Thanks for the bug report !
Normally v`1.0.1` and `1.0.3` only differ by some very minor patches (see our [releases](https://github.com/jscad/OpenJSCAD.org/releases) ), but it almost looks like the dev version is fetching a wrong version of `@jscad/csg` . I was able to reproduce locally, so I will let you know as soon as there is a fix

**Comment by kaosat-dev** [comment] 2017-11-01 19:55
@cbrunschen I have traced the issue, and the fix is almost ready (see https://github.com/jscad/csg.js/pull/62) , however I still do not understand how it could have impacted this repository, as Openjscad.org is still using an older version of CSG.js which did NOT have the change/bug.

Could you please tell me the version number of csg.js in your `node_modules/@jscad/csg` folder ? (this is very important for the whole project and my sanity)

**Comment by cbrunschen** [comment] 2017-11-01 20:14
Hi @kaosat-dev , thank you so much for digging into this!

The OpenJSCAD.org tree does not seem to have a folder node_modules anywhere that I can find?

**Comment by kaosat-dev** [comment] 2017-11-02 09:39
@cbrunschen No problem !
For `node_modules` I mean in your local install :)

**Comment by cbrunschen** [comment] 2017-11-02 17:02
@kaosat-dev , per the steps I took above,

> I just did a fresh sequence of:
> 
> git clone github.com - jscad/OpenJSCAD.org
> cd OpenJSCAD.org
> python -m SimpleHTTPServer 8001
> 
> pointed a web browser (Google Chrome, version Version 61.0.3163.100) at
> 
> http://localhost:8001/

... there is no folder `node_modules` nor any file `csg.js` present in my local install.

**Comment by kaosat-dev** [comment] 2017-11-02 17:32
ahhh sorry, so you used the prebuilt version ! doh' sorry, my bad @cbrunschen, sorry !
In that case the issue is clear !
So the source of it is now fixed, I will impact changes in this repo and you should be good to go !
I will let you know once it is available

**Comment by kaosat-dev** [comment] 2017-11-05 09:15
@cbrunschen it should now be fixed, can you do a fresh install and try again please ?

**Comment by cbrunschen** [comment] 2017-11-05 09:22
Gladly! From the local prebuilt install (just did a 'git pull', started a local web server and tried the example above (as well as a more complex one) and CSG.ConnectorList works as expected!

The version is also indicated as '1.0.4'. 

Many thanks!

// Christian

**Comment by kaosat-dev** [comment] 2017-11-05 10:38
glad it works :) You also helped us track down some internal issue with this bug so thanks for that :)
Have fun !

**Closed by kaosat-dev** 2017-11-05 10:38 UTC

**Comment by cbrunschen** [comment] 2017-11-05 10:56
I am indeed having fun! :) Thank you again!
(May I ask what the internal issue was?)

**Comment by kaosat-dev** [comment] 2017-11-05 12:23
sure ! we changed the internals of csg.js (the main dependency) considerably, and we forgot to expose CSG.ConnectorsList.
