### ISSUE TITLE
V1 viewer gets in bad state in which it wrongly thinks mouse button is down

### ISSUE THREAD

**Issue by donhatch** [jscad/OpenJSCAD.org#315] opened 2017-11-08 06:29 UTC
## Expected behavior:
Viewer should rotate as mouse pointer is moved only when left mouse button is down.

## Actual behavior:
Viewer often gets in a state where it is rotating even when left mouse button isn't down.

## Steps to Reproduce the Problem
  1. npm run start-dev
  2. open in browser: http://localhost:8080
  3. left mouse down in main display area
  4. with left mouse button down, move mouse pointer to the right until it's over the editor (or outside window)
  5. release left mouse button
  6. move mouse pointer back over main display area
  7. model is now rotating in response to pointer motion, as if it thinks the left mouse button was still down.

## Specifications:
 - Version: current repo source: commit b77c94809453d35282f54da2ce7e4be64f804aad
 - Platform: macbook pro
 - Environment: chrome 61.0.3163.100, local server

## Other Observations
Note that the latest repo source has this problem, but at this moment http://openjscad.org does *not* have the problem; this indicates the problem was introduced recently.

git bisect says the problem was introduced in this commit:

  commit 22d97955895fdbe724e07650524c7633909d7ec1
  Author: Mark 'kaosat-dev' Moissette <kaosat.dev@gmail.com>
  Date:   Thu Aug 10 09:20:34 2017 +0200

      fix(controls): changed camera controls to only work in 3d view
           * solved annoying issues with camera rotation when editing code

**Comment by kaosat-dev** [comment] 2017-11-08 09:59
Thanks for the bug report @donhatch 
Hmm I see the issue, this one and the one it solved are quite annoying, I'll look into fixing this.

**Comment by z3dev** [comment] 2017-11-09 05:21
Yes. I can reproduce,but a simple click anywhere resets.
It seems like expected behavior, as the click sets focus.
I could be wrong... but browsers are strange things.

**Comment by donhatch** [comment] 2017-11-09 18:18
Hi @z3dev, yes, the bad state can be corrected by clicking.
Sure, browsers are strange things, but that doesn't excuse the regression-- this was working perfectly well before the bad commit.

This failure to track the mouse button state is a common botch in user interaction: in general, if you want to track mouse button state, you have to listen for mouse-up on the *document*, not on the original element on which the mouse-down occurred.   The viewer code was doing that properly, before the bad commit broke it.

**Comment by kaosat-dev** [comment] 2017-11-09 18:40
@donhatch sorry but the behaviour before that commit was even more broken, since it made using the code editor a total pain

**Comment by kaosat-dev** [comment] 2017-11-09 18:48
That does not mean that you are not right about this bug though:)

**Comment by donhatch** [comment] 2017-11-09 19:15
Hi @kaosat-dev,  I think whether it seems more broken before or after that commit depends on what features you use.   Personally, I don't use the code editor, so the old bad behavior didn't bother me much.   But I find the new bad behavior to be a big obstacle to me being able to manipulate and examine the model.

In general, I expect ad-hoc editors in uis to be chronically broken and inadequate in all sorts of ways-- I think trying to get them to work well tends to be a never-ending losing battle, and makes you break other stuff.  Case in point here :-)

**Comment by kaosat-dev** [comment] 2017-11-09 19:59
Hi @donhatch  haha well I can related , not a fan of the code editor either, but I could be in the minority.
I played around with both versions and honestly even without the code editor, the current behaviour seems more natural to me.
Meh , you are right always an issue with Uis , too much subjective stuff!

A somewhat easy fix would be to just stop the mouse tracking on any mouse 'out' (trivial to add).
Although last time I added that behaviour to a viewer some people did not enjoy it either haha

**Comment by z3dev** [comment] 2017-11-09 23:20
Hmmm... I'm a BIG fan of the built in editor, as I use this functionality to write designs interactively via my Z3 Lab (There's automatic save to the server built in)

So, we have several takes on what would be right.... :)
It does seems strange to remain focused on the viewer. So I would favor this change.

**Comment by donhatch** [comment] 2017-11-09 23:49
mouseout (or mouseleave) wouldn't be a good criterion-- interaction (rotate or zoom) should continue until the mouse button is released, even if the mouse pointer has left the element.   This is especially important when the window is small and the user wants to do a large sweeping drag to perform a large rotate or zoom-- it would be maddening if mouse tracking stopped every time the pointer left the window.

The only way I've seen to get good interaction in a manipulator like this is to stop the mouse tracking on mouseup on the document.

**Comment by donhatch** [comment] 2017-11-10 00:20
To be precise-- it should listen for *mousedown* on the 3d view element
(so that part of the commit is correct-- it's good that mousedown on the editor or menu no longer initiates interaction)--  but it needs to listen for *mouseup* on the document instead.

**Comment by donhatch** [comment] 2017-11-10 01:39
Hi @kaosat-dev , it looks like this can be fixed (without re-breaking the editor)
in most-gestures/src/index.js, by changing the following lines:
```
    const mouseUps$ = fromEvent('mouseup', targetEl)
    const mouseMoves$ = fromEvent('mousemove', targetEl)
```
to these instead:
```
    const mouseUps$ = fromEvent('mouseup', document) // *not* targetEl!
    const mouseMoves$ = fromEvent('mousemove', document) // *not* targetEl!
```
However, that breaks `npm test` in most-gestures.  Not sure why.

**Comment by kaosat-dev** [comment] 2017-11-11 07:56
Hi @donhatch , good tracking job :)
Honestly , this really needs more consideration and experimenting on my end : things also need to work when Openjscad/ 3d viewer is not full page , and possibly with multiple ones on the same page etc.  (most-gestures is used by multiple 3d viewers that I do NOT want to break :D) 
I'll take a deeper look, but do not hold your breath just yet, sorry !

**Comment by z3dev** [comment] 2021-03-07 12:11
This is the V1 WEB UI so no further fixes are expected.

**Comment by z3dev** [comment] 2022-03-26 13:32
@donhatch please try openscad.xyz and let us know if this issue still exists. Things are a little different now.

if satisfied then please close this issue.

**Closed** 2022-05-11 12:57 UTC
Labels: will not fix, user interface
