### ISSUE TITLE
Browser use most of system ressources when rendering a script with rotate() method and an array of angles

### ISSUE THREAD

**Issue by scls19fr** [jscad/OpenJSCAD.org#357] opened 2018-02-19 09:03 UTC
## Expected Behavior

Render correctly without crashing

## Actual Behavior

Browser uses most of system ressources and seems to crash

## Steps to Reproduce the Problem

I'm new to programmatic CAD (OpenSCAD, OpenJSCAD, ImplicitCAD...).
I was trying to convert manually OpenSCAD code from https://www.thingiverse.com/thing:155001 to OpenJSCAD and
I put following code on https://openjscad.org

```js
function main() {
    enclosure_inner_length = 60;
    enclosure_inner_width = 40;
    enclosure_inner_depth = 30;
    
    enclosure_thickness = 2;
    
    cover_thickness = 3;

    p = lid2(enclosure_inner_length,enclosure_inner_width,enclosure_inner_depth,enclosure_thickness,enclosure_thickness/2+0.10,cover_thickness);

    return p;
}

function lid2(in_x, in_y, in_z, shell, top_lip, top_thickness) {
    sx = in_x/2 - 4;
    sy = in_y/2 - 4;
    sh = shell + in_z - 12;
    nh = shell + in_z - 4;

    p1 = union(
        cylinder(r=1.5, h = 15, $fn=32).translate([sx , sy, sh]),
        cylinder(r=1.5, h = 15, $fn=32).translate([sx , -sy, sh ]),
        cylinder(r=1.5, h = 15, $fn=32).translate([-sx , sy, sh ]),
        cylinder(r=1.5, h = 15, $fn=32).translate([-sx , -sy, sh ])
    );

    /* 
    // Work
    p2 = cube ([5.75, 10, 2.8])
        .translate([-5.75/2, -5.6/2, -0.7]);
    */
    
    // Doesn't work
    p2 = cube ([5.75, 10, 2.8])
        .translate([-5.75/2, -5.6/2, -0.7])
        .rotate([0,0,-45]);
    
    return union(p1, p2);

}
```

## Specifications

  - Version:  https://openjscad.org website (1.6.0)
  - Platform: Ubuntu 17.10
  - Environment: Chromium Version 64.0.3282.140 (Build officiel) Built on Ubuntu , running on Ubuntu 17.10 (64 bits)

**Comment by z3dev** [comment] 2018-02-21 07:20
@scls19fr Thanks for the information.

The issue is caused by the obj.rotate([0,0,-45]
That version of the rotate() function does not accept an array of angles. Please use obj.rotateZ(-45)

FYI, we are working a new version of the API which resolves the differences in the function names, parameters, etc. But that probably won't be available for a few more releases.

**Comment by z3dev** [comment] 2020-03-04 09:26
No reply. Closing.

**Closed by z3dev** 2020-03-04 09:26 UTC
