### ISSUE TITLE
Problems with use of Math.Floor and with comparisons of inexact data.

### ISSUE THREAD

**Issue by briansturgill** [jscad/OpenJSCAD.org#1075] opened 2022-04-25 18:21 UTC
## General Bug Report
I recently experiment with making my CSharp port of JSCAD using single precision arithmetic. (This was in hopes of using some special Microsoft features that would speed things like Transformations, but only used Single precision.) This experiment failed, but it did uncover some general bugs in JSCAD. These all fall into the realm of side effects of floating point precision.

I'll start with a detailed explanation of the first issue I encountered. This was AFTER the cos/sin (with rezero) changes that were
recently made. I have removed those changes from my code base, this new way seems more robust and the rezero functions are no longer needed.
So I immediately hit three bugs in ellipse.cs... I'm showing you what it would look like in ellipse.js.
The first one (line 58) is a totally inappropriate use of Math.floor.
The problem is simple... I was getting a 4.9999... value that was getting chopped to 4.
The others are basically incorrect comparisons of a calculated value (thus inprecision) with Math.PI*2.
Thus I created the "Equalish" routines. Basically before doing a floor it checks to see if the value is "Equalish" to the ceiling,
choose Ceiling if it is, otherwise it does the floor.
Likewise lessThanish... first checks "Equalish" then if it is not Equalish it does the < comparison.
I have include my CSharp versions of these routines at the end.
Also a complete list of the changes I made in the primitives and extrusions... I'm sure I'll find more and will let you know when I do.
```
ellipse.js: 58
segments = Math.floor(segments * (rotation / (Math.PI * 2)))
segments = floorish(segments * (rotation / (Math.PI * 2)))
--
ellipse.js: 64
segments = (rotation < Math.PI * 2) ? segments + 1 : segments
segments = lessThanish(rotation, Math.PI * 2) ? segments + 1 : segments
--
ellipse.js: 71
if (rotation < Math.PI * 2) points.push(centerv)
if (lessThanish(rotation, Math.PI * 2)) points.push(centerv)
```

--- Here's the complete list of the "ish" changes' I've made so far (translated to javasscript and your current line numbers.)
--- Note, I just discovered some changes had been made to extrudeRotate since I last pulled. line might be off a few...
please let me know if I need to disambiguate!---
```
extrudeRotate.js: 50
if (totalRotation <= 0.0) totalRotation = (Math.PI * 2)
if (lessThanOrEqualish(totatalRotation, 0.0) totalRotation = (Math.PI * 2)
--
extrudeRotate.js: 55
segments = Math.floor(Math.abs(totalRotation) / anglePerSegment)
segments = floorish(Math.abs(totalRotation) / anglePerSegment)
--
cylinderElliptic.js: 67
const slices = Math.floor(segments * (rotation / (Math.PI * 2)))
const slices = floorish(segments * (rotation / (Math.PI * 2)))
--
cylinderElliptic.js: 120
if (rotation < (Math.PI * 2)) {
if (lessThanish(rotation < (Math.PI * 2))) {
--
ellipse.js: 58
segments = Math.floor(segments * (rotation / (Math.PI * 2)))
segments = floorish(segments * (rotation / (Math.PI * 2)))
--
ellipse.js: 64
segments = (rotation < Math.PI * 2) ? segments + 1 : segments
segments = lessThanish(rotation, Math.PI * 2) ? segments + 1 : segments
--
ellipse.js: 71
if (rotation < Math.PI * 2) points.push(centerv)
if (lessThanish(rotation, Math.PI * 2)) points.push(centerv)
--
roundedCylinder.js: 64
const qsegments = Math.floor(0.25 * segments)
const qsegments = floorish(0.25 * segments)
--
// My best guess on this one is that they had the "floorish" sort of issue and used
// Math.round to "fix" it, but that really isn't the appropriate way.
// And it could fail on edge cases.
ellipsoid.js: 41
const qsegments = Math.round(segments / 4)
const qsegments = floorish(segments / 4)
```

--- Below is my C# version of the routines... you shouldn't have trouble making the JS version. ---
--- The value C.EPS is 1e-5 which you generally reference as EPS everywhere. ---
```C#
    public static bool Equalish(double a, double b, double epsilon = C.EPS)
    {
        if (a == b)
        { // shortcut, also handles infinities
            return true;
        }

        var absA = Math.Abs(a);
        var absB = Math.Abs(b);
        var diff = Math.Abs(a - b);
        if (double.IsNaN(diff))
        {
            throw new ValidationException("Should never have NaN.");
        }
        return diff <= epsilon;
    }

    public static bool GreaterThanOrEqualish(double a, double b, double epsilon = C.EPS) {
        if (Equalish(a, b, epsilon)) {
            return true;
        }
        return a >= b;
    }

    public static bool GreaterThanish(double a, double b, double epsilon = C.EPS) {
        if (Equalish(a, b, epsilon)) {
            return false;
        }
        return a > b;
    }

    public static bool LessThanOrEqualish(double a, double b, double epsilon = C.EPS) {
        if (Equalish(a, b, epsilon)) {
            return true;
        }
        return a <= b;
    }

    public static bool LessThanish(double a, double b, double epsilon = C.EPS) {
        if (Equalish(a, b, epsilon)) {
            return false;
        }
        return a < b;
    }

    public static int Floorish(double a, double epsilon = C.EPS)
    {
        var a_ceil = Math.Ceiling(a);
        if (Equalish(a, a_ceil, epsilon)) {
            return (int)a_ceil;
        }
        return (int)Math.Floor(a);
    }
```

**Comment by z3dev** [comment] 2022-04-26 11:47
@briansturgill i have read this several times now in order to understand the issues.

first, the changes made by @platypii were to correct the primitive shapes, and make sure those are water-tight meshes.

second, you're trying to solve something with the changes but I'm not certain of the issues. Maybe a slightly better example would help.

third, although the 'math' might be off, there are expected results when using segments, start rotation, and end rotation. These three parameters make a pretty spicy problem, which needs to be consistent.

forth, there are utility functions to assist with the calculation of segments. Users may want to have a specific number of segments, or a specific length of segments.

**Comment by platypii** [comment] 2022-04-26 15:56
I am still looking into this, so far I've only looked at the ellipse feedback, but I am not sure I agree with your issue. Maybe you could give a specific example ellipse that demonstrates the problem?

The code is different for full rotation vs less-than-full rotation. Which case do you think contains a bug? Assuming the case of a full rotation, the `rotation` is set on line 45:
```js
let rotation = (Math.PI * 2)
```
Since the defaults have `startAngle < endAngle`, the rotation will be re-set on line 47:
```js
rotation = endAngle - startAngle
```
Which is still exactly `Math.PI * 2`. Do you agree that rotation is exactly `Math.PI * 2` there?

Now looking at line 58 which you propose to change.
```js
segments = Math.floor(segments * (rotation / (Math.PI * 2)))
```
Since `rotation === Math.PI * 2`, the latter part of the formula will evaluate to `(rotation / (Math.PI * 2)) === 1`. Exactly one. So that implies that `Math.floor(segments * 1) === segments`. So I am unable to reproduce your `4.9999` bug.

I am also not sure your changes remove the need for `rezero`, because that is fixing a different issue than the one you are pointing out (not related to segments?).

Is it possible you are hitting a difference between single and double precision `Math.PI * 2`? That wouldn't be an issue in JS.

I'm sure there are bugs (I've found many :smile:) but I'd just like to understand a bit more what the issue is here.

**Comment by platypii** [comment] 2022-04-26 18:55
For ellipses, it seems this is not actually a bug in JSCAD. But it is a bug when porting JSCAD to a new language that has mixed `float` and `double` precision numbers.

Relying on exact floating point arithmetic seems valid in this particular case in javascript, but we could make the code a bit more robust for porting by making the logic of "is this a full or partial rotation?" more explicit. 

The code could be restructured to have a `isFullRotation` boolean variable. This could make the code easier to logically port to other languages. I'm not sure that "portability" would be considered an explicit goal of the project, but in this case I think it would also make the code easier to read.

**Comment by briansturgill** [comment] 2022-04-26 19:55
OK, people keep looking at specific cases (for example at Math.PI*2) and not looking at the bigger picture.
I see this happening all through the JSCAD code... simple comparisons are made on numbers that are not safely considered exact.
What first triggered this was the fact I was using Single precision, but that is only because your normal unit test started failing.
The problem isn't the single precision, but rather that comparison and Math.floor were making invalid assumptions about the exactness of incoming data.
First of all I will point out that Math.PI*2 is not the same as 2pi. (pi being the irrational number). There is immediately error there by necessity. ANY code that does a simple floating point comparison to Math.PI*2 is flat out wrong.

The places where I used the "ish" routines were all places where you are checking a coordinate value. And coordinates in all computational geometry packages are not specific points. Leeway has to be allowed.

The unit tests in JSCAD may be fooling you... they are often integer values... I don't think they are catching edge cases.
Having you considered doing what used to be called "monkey" testing (after the old joke about how many typing monkey it would take to produce Shakespeare)? It's a form of random testing where you literally throw random values (that are in the allowed range) at routines and then check validity of output.

I'm not the only one seeing this problem... the guy that wrote recently about his "willow" project was saying the same thing... there's a lot of places in JSCAD where absolute checks are done when range checks should be done instead.

**Comment by platypii** [comment] 2022-04-26 20:15
We understand that. The challenge is where exactly to put fuzzy checks vs exact checks. There are lots of places in the code base with epsilon checks, and there are certainly more places needed.

My point though is that I presented an argument why, in the ellipse case, I can prove that the checks are correct as-is, assuming we're in a double-only environment like javascript. This has nothing to do with the irrational number 2*Pi, just the floating point representation of `Math.PI * 2`. Which is why my comment focused on refactoring for clarity and robustness on other platforms, not necessarily fixing a bug. I don't agree with your categorical statement "there is immediately error there by necessity". It is possible to reason deterministically about certain floating point code.

That being said, if we can improve the code whether for correctness, portability, or readability, I am enthusiastically in favor of it. I intend to review all of the lines you've suggested in the code to see if they should be changed.

**Comment by briansturgill** [comment] 2022-04-26 20:22
A circle has a circumference of 2pi, not Math.PI*2, so YES there is definitely error there.

**Comment by hrgdavor** [comment] 2022-04-26 20:27
> A circle has a circumference of 2pi, not Math.PI*2, 

@briansturgill I am a noob, could you point to a link or an explanation

**Comment by briansturgill** [comment] 2022-04-26 23:03
A circle's circumference is 2 "pi" (the Greek letter) radians.
Pi represents an irrational number which is: 3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706...
The ... means it goes on literally forever... it has an infinite length.
Math.PI is a JavaScript floating point number that is EXACTLY: 3.141592653589793
It is finite.
Meaning any attempt to use it for the circumference of a circle will be off by:
0.00000000000000023846264338327950288419716939937510582097494459230781640628620899862803482534211706...
As JSCAD really only cares about number bigger than 1e-5 (0.000001). It is often not an issue.
However it is big enough that it can cause a normal floating point number comparison to fail...
Frequently in JSCAD you'll see Math.PI*2 being used as the boundary condition for the end of a circle.
That works, but you need to be using an "ish" comparision... i.e. see that it is within the bounds +/-1e-5 from Math.PI.

**Comment by z3dev** [comment] 2022-04-26 23:04
> A circle has a circumference of 2pi, not Math.PI*2, so YES there is definitely error there.

Tis so with any CPU based math, float, double, integers, etc.

All calculations are inherently inaccurate. If the code can be rewritten (and it has been) to eliminate comparisons between inaccurate numbers then there's improvements.

**Comment by briansturgill** [comment] 2022-04-26 23:22
One odd note... if the routines were written in degrees, not radians, much of the pain would be gone.

**Comment by gilboonet** [comment] 2022-04-27 19:42
Before I used OpenSCAD then JSCAD, I used Povray and its source is C++, maybe it can give you some hints that JSCAD cannot.
Do you have an use case where Math.PI value is not precise enough ? I'm not specialist but I already use code like your *ish and I'm sure that we all do the same, use comparaisons adapted to our needs, more precisely to the granularity of our needs. What you say about Math.PI is odd, we all know what is PI and also that javascript has limitations that we must cope with, what would you propose to be able to handle PI infiniteness and won't cripple JSCAD performances ?

**Comment by z3dev** [comment] 2022-07-05 12:14
> I'm not the only one seeing this problem... the guy that wrote recently about his "willow" project was saying the same thing... there's a lot of places in JSCAD where absolute checks are done when range checks should be done instead.

@briansturgill can you provide a reference for the "willow" project? It would be good reference for this issue.

**Comment by briansturgill** [comment] 2022-07-05 19:12
> > I'm not the only one seeing this problem... the guy that wrote recently about his "willow" project was saying the same thing... there's a lot of places in JSCAD where absolute checks are done when range checks should be done instead.
> 
> @briansturgill can you provide a reference for the "willow" project? It would be good reference for this issue.

The "willow" project was pointed out to me by @hrgdavor a couple of months ago. I had assumed at the time it was from an OpenSCAD.org discussion, but I cannot find it searching for it. Perhaps @hrgdavor will remember where the reference originated. Basically the guy was tired of problems in JSCAD and was writing his own CAD... I think it was in C++ and it definitely was going to use large integer arithmetic (if you want to see an example of that, see: http://www.angusj.com/delphi/clipper.php). The use of integers instead of floating point is kind of the latest fad in CAD.
I've seen it said that CGAL uses rational arithmetic, and it of course is very slow (and surprisingly still has a fair bit of error).

**Comment by z3dev** [comment] 2022-07-05 21:09
Ah... I see. It's actually called Walnut. See the discussion on trying to integrate/ use as part of JSCAD.

**Comment by platypii** [comment] 2022-07-06 03:17
Side note, but I don't see how switching to BigInt rationals really helps. As soon as there is any nontrivial rotation you'll end up with irrational numbers, and you'll need to approximate again anyway.

It seems like every system will approximate at some level. Maybe some operations can be made precise with rationals that floating point cannot, I'm not sure. But overall it seems like it would significantly increase complexity, hurt performance, and ultimately still have possible errors.

Especially in JS with no first class integer types, improving the stability and robustness of the floating point algorithms is the way to go.

**Comment by briansturgill** [comment] 2022-07-07 03:36
> Side note, but I don't see how switching to BigInt rationals really helps. As soon as there is any nontrivial rotation you'll end up with irrational numbers, and you'll need to approximate again anyway.
...
I agree, I don't really think it's that much of a help and it's a definite performance hit.
Note, there might be a good reason on the horizon though. I'm thinking that they may be thinking that GPU hardware could handle large ints better than floating point.
A lot of CAD research these days is more display oriented than creation of model oriented.
One problem I've had finding a good 3D booleans algorithm is that many of them are geared wrong.

BTW, I think that the move to a new 3D algorithm will require them all to be triangulated. Booleans are MUCH easier on triangles and it has the added benefit of having control over inserted point values as you can handle both sides of an intersection at the same time.

**Comment by z3dev** [comment] 2022-08-13 11:13
I'm closing this as there's very little to 'take home'. The issues with floating point is well known and documented all across the internet. Let's focus on discrete examples where the floating point is failing, and try to improve those calculations.

**Closed by z3dev** 2022-08-13 11:13 UTC
