### ISSUE TITLE
Birthday Balloons

### ISSUE THREAD

**Issue by IanSC** [jscad/OpenJSCAD.org#907] opened 2021-09-10 02:54 UTC
<img width="449" alt="Screen Shot 2021-09-10 at 10 35 07 AM" src="https://user-images.githubusercontent.com/8453489/132791331-02579398-a668-4beb-821e-5a13ff1b00e7.png">

## Expected Behavior
great birthday celebration

## Actual Behavior
deflated balloons ruining the party

## Steps to Reproduce the Problem

  1. visit https://www.openjscad.xyz/#
  2. load 'Birthday Balloons' example
  3. Age 7
  4. 77, 777 is okay

## Specifications

  - Version:
  - Platform:
  - Environment: (browser, local server, node.js etc)

**Comment by z3dev** [comment] 2021-09-28 08:01
This issue has been present from the initial V2 release; April 2021

**Comment by z3dev** [comment] 2021-09-29 03:30
OH PAIN!!!!

It turns out that the linear extrude for '7' is failing, and producing artifacts (extra polygons).

![issue907_1](https://user-images.githubusercontent.com/8969165/135198067-aee476dc-6f6f-43c8-8060-a7c8cf5d5530.png)

Internally, the call to intersetGeom3Sub() is producing those artifacts. So, the BSP algorithms are having issues with constructing trees for the polygons.

I've reviewed the code again, comparing V1 to V2. The V2 code is sound but there was one special change made for performance in Node.js
```
        let index = 0 // default
        index = Math.floor(polygontreenodes.length / 2) // BIG PERFORMANCE BOOST
```
But that one change is causing issues within the BSP logic. Switching to the default (0) corrects all issues.

This is NOT good news.

**Comment by hrgdavor** [comment] 2021-09-29 06:59
@z3dev could you re-run those perf tests for these 2 different index start points? Maybe there is a slight chance that the fix with stop condition affects performance difference between the two.

**Comment by z3dev** [comment] 2021-09-29 07:26
@hrgdavor thanks for the suggestion.

i think there's some issues with the Node.toClip() function, and will try to get a small test case.
This issue may be affecting other functions that use the boolean functions as well, such as extrusions, project, etc.

**Comment by hrgdavor** [comment] 2021-09-29 07:47
Now that I think of it, changing start index might not be a fix, but just moving the issue to a different edge case. This is just a suspicion. I agree with trying to postpone changing the index, as it affects maaaany test cases.

**Comment by z3dev** [comment] 2021-09-29 07:53
This is definitely an edge case. This is only happening for...
- character '7' (probably due to the angle of the sides)
- round corners with segments: 32

So, yeah. Another deep dive is required.

**Comment by z3dev** [comment] 2021-09-30 09:03
A little more information... inside intersectGeom3Sub(), the BSP trees are called to clip polygons from each of the trees. This is the call that produces the artifact polygon.

`  a.clipTo(b)`

I'm going pretty deep into the trees now, and understanding things further. Something is definitely hitting an edge case, which leaves the artifact polygon in the tree.

**Comment by hrgdavor** [comment] 2021-09-30 09:15
I am thinking of ways to help with visualising stuff like this. I have an idea how to anble pausing the code in debugger but also being able to view stuff currently debugged.

I have been using watch expression to dump polygon data into console, but I think I can make it possible to also visualize points by calling jscadDebug(....code to produce geometry from local data ...)

**Comment by z3dev** [comment] 2021-10-02 06:33
Another update... I went way way down the boolean road, but could not find any kind of bug or condition that produced that artifact.

So... I tried V1 booleans on the same set of polygons. WA LA! THE SAME BUG!!! 🐛 

So, the technique being used by slice.toPolygons() is not going to work. An alternative approach is required.

FYI, this bug affects everything in the extrude family.

**Comment by z3dev** [comment] 2021-10-02 06:39
[bug_V1.js.txt](https://github.com/jscad/OpenJSCAD.org/files/7270969/bug_V1.js.txt
[bug_V2.js.txt](https://github.com/jscad/OpenJSCAD.org/files/7270972/bug_V2.js.txt)
)

**Comment by hrgdavor** [comment] 2021-10-02 11:02
Interesting. It is good that you have pinpointed the culprit.

**Comment by t1u1** [comment] 2022-02-04 05:52
I was trying to find more and simple examples that reproduce this problem. I have found these so far:

![extrudeGlitch](https://user-images.githubusercontent.com/90307689/152479128-58b7021f-c2b0-45d4-9e88-ab5d86283544.png)

The letter N requires only 13 segments.

Code to reproduce this is [here](https://gist.github.com/t1u1/81cf1c9e4d4cce1d0eaf8b1ec6ebff5d).

I will now try to find even smaller examples.

**Comment by t1u1** [comment] 2022-02-04 14:33
> Internally, the call to intersetGeom3Sub() is producing those artifacts. So, the BSP algorithms are having issues with constructing trees for the polygons.

AFAICT, these functions are being called to create caps at start and end. The calling hierarchy is: 
extrudeLinear -> extrudeSlices -> for start and end caps: slice.toPolygons()

One workaround could be to expose `capStart` and `capEnd` options in `extrudeLinear`'s options, just like in other extrude functions. Then the user has the option to create the caps themselves, which is easy for trivial cases.

Another workaround could be to use simplified logic in `extrudeLinear ` when twistAngle == 0. In this special case, constructing the walls might be much more straight forward.

@z3dev Please let me know if that makes sense, and whether you can take this up. If you wish, I can attempt a PR too, but it might take a lot of time, since I am not that familiar with the code.

**Comment by z3dev** [comment] 2022-02-07 06:07
@t1u1 can you try changing the ‘segments’ parameter value?

in previous tests, I found some solutions if the segments was adjusted.

**Comment by t1u1** [comment] 2022-02-07 06:51
@z3dev Changing the segments works randomly. If segments == 128 works for model dimension of 200mm, it fails for 201mm, and so on.

IMO, this is a serious bug (that is, it prevents JSCAD from being used for any serious application). For example, the models I am building will be useful for calibrating optical elements used by hobby astronomers, such as mirrors or lenses. The precision required is not high, but rogue polygons are definitely not acceptable.

**Comment by hrgdavor** [comment] 2022-02-07 07:52
@t1u1 is your main problem with using letters and numbers ? I can look into the problemnext week, or maybe I catch some time this week, but that does not mean I can guarantee a fix.

As a workaround you could use a ttf font, we have a working example  mentioned here: https://github.com/jscad/OpenJSCAD.org/issues/72

**Comment by t1u1** [comment] 2022-02-07 09:19
> is your main problem with using letters and numbers ?

No, no. Letters and numbers are just a test case.

My model looks like this:
![model](https://user-images.githubusercontent.com/90307689/152309958-a084d722-38ac-4282-aaec-4f6619ed8a7f.png)

**Comment by hrgdavor** [comment] 2022-02-07 09:30
@t1u1 could you share that script ? and params when problems happen ?

**Comment by t1u1** [comment] 2022-02-07 11:10
> could you share that script ? and params when problems happen ?

It's not a script. It's a webapp. I could have still tried to share it, but it seems useless because its geometry is much more complex than the simple examples reported here.

Did you try the script shared in my previous comment: https://gist.github.com/t1u1/81cf1c9e4d4cce1d0eaf8b1ec6ebff5d

I have spent days trying to create simpler examples, but it's not easy. The  bug is frequent but brittle; it needs just the right conditions to show up. And we don't have any idea about what those conditions are.

**Comment by hrgdavor** [comment] 2022-02-07 11:25
@t1u1 some operations are more brittle than others. seing the script might allow me to propose workarounds.
It is possible some issues are caused by booleans. and is also possible there are more than one issue at hand.

**Comment by t1u1** [comment] 2022-02-07 11:33
@hrgdavor This particular issue is happening in intersectGeom3Sub(), just as @z3dev has described. I have stepped through the code, and verified that the problem exists there by looking at its output and the output of previous steps. I think @z3dev 's analysis is spot on.

**Comment by hrgdavor** [comment] 2022-02-07 11:45
What I noticed here in example from @z3dev is that either 2d part of the process is creating a case that breaks extrude. either the 2d starting model is faulty or extrude has a bug ...

after such faults are introduced, stuff down the line will break too.

![issue907_1](https://user-images.githubusercontent.com/8969165/135198067-aee476dc-6f6f-43c8-8060-a7c8cf5d5530.png)

**Comment by t1u1** [comment] 2022-02-07 11:58
> What I noticed here in example from @z3dev is that either 2d part of the process is creating a case that breaks extrude. either the 2d starting model is faulty or extrude has a bug ...

The location of the bug is already pinpointed. I suggest reading @z3dev's comments again.  The problem is in the part that creates the polygons for the end caps. These polygons are created by intersecting the polygons of the wall with a large polygon that covers the slice. The bug exists in the logic that computes this intersection.

**Comment by hrgdavor** [comment] 2022-02-07 12:15
@t1u1 I can likely fix issues with those texts by making a custom extrude function easier than fixing the existing one. Would this be helpful to you ?

**Comment by t1u1** [comment] 2022-02-07 12:28
> @t1u1 I can likely fix issues with those texts by making a custom extrude function easier than fixing the existing one. Would this be helpful to you ?

Thanks, but I am not sure I understand. Will the custom function only work with texts? There is no text in my models, only geometry created from booleans as shown in the picture.

**Comment by hrgdavor** [comment] 2022-02-07 12:34
idea is that it should work with all proper 2d shapes.... if the 2d shape does not look broken, it should work.. ... I tested the number 7 and it looked ok in 2D, but got messed up by extrude. I just have a feeling it would be easier for me to create a new extrude than fix the current one. at least for this simple case with only extruding 2d shape straight up.

**Comment by z3dev** [comment] 2022-02-07 12:35
It’s the TOP and BOTTOM caps that have issues. Not extruding the walls.

**Comment by hrgdavor** [comment] 2022-02-07 12:38
@z3dev hm, ok, I could look into that then

**Comment by z3dev** [comment] 2022-02-07 13:05
FYI, I have been playing with 2D boolean libraries to remedy these issues, as the 3D booleans pretty much fail when working with complex planar polygons. It looks promising but even the 2D libraries have issues. I’ll post updates going forward, and maybe some code if there are some improvements.

**Comment by platypii** [comment] 2022-02-07 16:51
It seems like a special case of extrudeLinear when twist = 0 would be really easy to make work correctly without these artifacts. Would likely be much faster too. However that just hides the problem. Fixing `intersectGeom3Sub` is the real solution. I am also looking into it.

**Comment by hrgdavor** [comment] 2022-02-07 17:03
if the issue is only with caps, then the twist is not the problem. The caps are just rotated, so a new code that makes caps properly would work just fine with or without the twist.

**Comment by platypii** [comment] 2022-02-07 23:17
It seems like intersectGeom3Sub is really just being used here to split non-convex polygons into convex polygons for the caps. It might be better to just implement a triangulation algorithm? For example, [Earcut](https://github.com/mrdoob/three.js/blob/master/src/extras/Earcut.js)

**Comment by platypii** [comment] 2022-02-08 02:54
The bug happens BEFORE the extrusion!! The geometry is not closed! This causes the extrusion to "leak" through the gap.

I found this when I tried to compute the outline of the geometry. The topological sort in `toOutlines` proved it. The "7" example has a discontinuity between `17.980817485911114,20.804759900888893` and `17.980817485911114,20.804896567511115`. Right where the artifact appears.

When you run the following script, it gives error:
```js
geom2.toOutlines(text2d("7", 2, 32))
```

```
Error: the given geometry is not closed. verify proper construction
```

<details>
  <summary>script</summary>

```js
const jscad = require('@jscad/modeling')

const { union } = jscad.booleans
const { extrudeLinear } = jscad.extrusions
const { hullChain } = jscad.hulls
const { circle } = jscad.primitives
const { vectorText } = jscad.text
const { translate } = jscad.transforms
const { geom2 } = jscad.geometries

// Build text by creating the font strokes (2D)
const text2d = (input, characterLineWidth, segments) => {
  const lineRadius = characterLineWidth / 2
  const lineCorner = circle({ radius: lineRadius, segments: segments })
  const lineSegmentPointArrays = vectorText({ x: 0, y: 0, input }) // line segments for each character
  const lineSegments = []
  lineSegmentPointArrays.forEach((segmentPoints) => { // process the line segment
    const corners = segmentPoints.map((point) => translate(point, lineCorner))
    const hull = hullChain(corners)
    lineSegments.push(hull)
  })
  return union(lineSegments)
}


const main = () => {
  const height = 2
  const obj2d = text2d("7", 2, 32)
  const obj3d = extrudeLinear({ height }, obj2d)
  geom2.toOutlines(obj2d)
  return obj3d
}

module.exports = { main }
```

</details>

**Comment by t1u1** [comment] 2022-02-08 03:43
> Error: the given geometry is not closed. verify proper construction

Indeed, I saw this error too. But I thought `toOutlines()` is also buggy, or I am not using correctly!

What you say makes a lot of sense now :+1:

**Comment by platypii** [comment] 2022-02-08 08:49
I made a script to mend the gaps in a polygon to make it closed. It looks for vertices with mismatched in/out edges, and then merges the closest vertex that fills the gap. It fixed all the examples from this thread, if called before extrudeLinear. @t1u1 this might help your designs?

```js
/**
 * Mend gaps in a 2D geometry to make it a closed polygon
 */
const repairGeom2 = (geometry) => {
  const vertexMap = {} // string key to vertex map
  const edgeCount = {} // count of (in - out) edges
  for (let edge of geometry.sides) {
    const inKey = edge[0].toString()
    const outKey = edge[1].toString()
    vertexMap[inKey] = edge[0]
    vertexMap[outKey] = edge[1]
    edgeCount[inKey] = (edgeCount[inKey] || 0) + 1 // in
    edgeCount[outKey] = (edgeCount[outKey] || 0) - 1 // out
  }
  // find vertices which are missing in or out edges
  const missingIn = Object.keys(edgeCount).filter((e) => edgeCount[e] < 0)
  const missingOut = Object.keys(edgeCount).filter((e) => edgeCount[e] > 0)
  // pairwise distance of bad vertices
  missingIn.forEach((key1) => {
    const v1 = vertexMap[key1]
    // find the closest vertex that is missing an out edge
    let bestDistance = Infinity
    let bestReplacement = undefined
    missingOut.forEach((key2) => {
      const v2 = vertexMap[key2]
      const distance = Math.hypot(v1[0] - v2[0], v1[1] - v2[1])
      if (distance < bestDistance) {
        bestDistance = distance
        bestReplacement = v2
      }
    })
    console.log(`Repair gap ${v1} → ${bestReplacement} dist ${bestDistance}`)
    // merge broken vertices
    geometry.sides.forEach((edge, i) => {
      if (edge[0].toString() === key1) edge[0] = bestReplacement
      if (edge[1].toString() === key1) edge[1] = bestReplacement
    })
  })
  return geometry
}
```

**Comment by t1u1** [comment] 2022-02-08 10:49
@platypii Thanks! The examples indeed work fine now. However, my design still fails in the same way as earlier. This is progress because it is clearly a different type of failure. (As further confirmation, the `toOutlines()` call works fine on my design, with or without the repairGeom2() call).

I will try further to isolate the problem now, and raise a different issue.

**Comment by t1u1** [comment] 2022-02-08 11:01
Holdon! One case from the examples here is still showing a problem!

See this script: https://gist.github.com/t1u1/a8300974af1f7c8f213cdc7541cb348d

The `text("4", 2, 1, 26)` object still has this glitch, even after calling repairGeom2()

**Comment by z3dev** [comment] 2022-02-08 12:40
Nice investigation @platypii 

There are similar ‘closing’ issues with projections, as projecting a point to a plane is never floating point correct. Snapping points to an ESP seems to help but doesn’t solve the issues completely.

Just feedback…

**Comment by t1u1** [comment] 2022-02-09 13:55
I found a few other glitches (just trying to help find more test cases).

Test script is here: https://gist.github.com/t1u1/6d5a1c6f6494f61394ca7735a53aad78

With `repairGeom2()` :
![moreGlitchesRepair](https://user-images.githubusercontent.com/90307689/153215185-25bb3eb7-37d0-47d7-be91-36723189dffb.png)

Funnily, some of these work better without `repairGeom2()`:

![moreGlitches](https://user-images.githubusercontent.com/90307689/153215220-19e9af6c-ea88-435d-988a-004d1c7806a9.png)

**Comment by t1u1** [comment] 2022-02-09 14:04
@platypii Perhaps there is a small bug in `repairGeom2()`, which when fixed will make all the tests pass. I couldn't understand its logic so can't offer any suggestions. 

Thanks for looking!

**Comment by hrgdavor** [comment] 2022-02-09 14:30
I have discussed this with  @platypii , and the repairGeom2() was working properly, but creation of caps using booleans intersectGeom3Sub created more edge cases. 

So he made code that handles more cases better by using repairGeom2() and earcut algorithom taken from threejs(which they took from somewhere else). We discussed this on discord, he is still working on this, but he could have a good solution soon.

We would like this not to happen in boolean ops, but having a workaround in the meantime is also good.

**Comment by z3dev** [comment] 2022-02-12 08:32
OK. Two days of deep dive into the BSP trees and here's what I found.

Basically, the Node.clipTo() function has some issues. If you have ever looked into the code, you find some funny looking loops that use a 'stack' to control processing through the trees. If you think about this, basically the order of the calls are determined by the stack, which is created in a pretty strange fashion.

Why is that important? So, the trees basically 'clip' polygons by planes, and if the polygon is split then new polygons are added to the tree (in front of the plane and/or in back of the plane). There's a lot of planes (nodes), and each plane clips ALL polygons (old or new). The order of clipping is important, and controls the creation of new polygons.

THE BUG is basically caused by the unnecessary splitting of new polygons, i.e. split, split, split...

Just to prove my point, you can change the order by changing the selection of bestpoly (index) in Node.addPolygonTreeNodes(). Try the random version, and you'll see strange artifacts at different angles, etc. There's no perfect index for all designs, even 0 will fail sometimes.

I think the best solution would be to rewrite the Node.clipTo() to traverse the tree (in order), and see if that solves the issues.

Let me know if any other insights have been made.

P.S. I confirmed that the logic of splitPolygonByPlane() is rock solid. That's not the issue here.

**Comment by platypii** [comment] 2022-02-14 07:20
@t1u1 can you try out my earcut branch?
https://github.com/platypii/OpenJSCAD.org/tree/earcut

It uses a combination of the repair function, and a new earcut triangulation algorithm for the caps. It's worked on all the examples I've tried.

This does not fix floating point issues in the BSP tree code, it just avoids using the BSP tree for extrusion. The nice thing about the earcut triangulation algorithm is that it only uses existing vertices, it does not create new ones, so it should be less susceptible to floating point errors.

![Screenshot at 2022-02-12 00-03-01](https://user-images.githubusercontent.com/1766297/153703156-d4d94362-80fd-43df-90fb-ce115f2ecafc.png)
![Screenshot at 2022-02-13 23-19-15](https://user-images.githubusercontent.com/1766297/153817675-688a4bb7-96e1-4982-af3c-8f5ea5e5b0f3.png)

**Comment by t1u1** [comment] 2022-02-14 12:38
@platypii Woohoo! I confirmed that your branch works fine with all the examples in this issue so far. A few questions:

1. Why is R and B appearing dark in your screenshot? On my system only R appears dark, B doesn't. Is something wrong with the normals?
2. I would love to test your branch in my webapp. Is there an easy way to do this by publishing it to npm? (I tried a local way of doing it, but it still picks up the published version. I am not an expert in npm)

**Comment by hrgdavor** [comment] 2022-02-14 12:51
1. it could be that those are inverted, or simply lighting issue in the current render code.

**Comment by z3dev** [comment] 2022-02-14 12:57
> The nice thing about the earcut triangulation algorithm is that it only uses existing vertices, it does not create new ones, so it should be less susceptible to floating point errors.

That’s a huge improvement. As I’ve been improving the internals, the key is reuse of the vertex (points) as any calculation just adds floating point errors.

Thanks a lot @platypii

**Comment by platypii** [comment] 2022-02-14 15:44
The lighting on R and B is something I'm still investigating. I wouldn't be surprised if related to #985.

The reason for the change in "B" you saw, is that I took a screenshot first and then subsequently made a small fix to the plane calculation. Specifically [this change](https://github.com/jscad/OpenJSCAD.org/commit/90f19719ed1e073a425e20b05f0d35f2d15b758b#diff-81a23638bf3e80fcf444137d3c35f8ad947b18f3daf2122cde8f72acf5984cd2) to `poly3.invert` fixed the  "B". I'm not yet sure why.

**Comment by platypii** [comment] 2022-02-15 01:24
After some investigation, determined that a bug in `slice.calculatePlane` returns `[0,0,0,0]` when it hits a self-edge. I fixed this in two places: 1) `repairSlice` function now removes self-edges, and 2) `slice.calculatePlane` will skip a self-edge if it encounters one.

The updates are on my `earcut` branch

**Comment by t1u1** [comment] 2022-02-15 06:30
@platypii Cool! Confirming that the latest `earcut` branch works fine on all the examples posted here, including the correct brightness on "R". However, noting a few new failures:

![hb-xyz](https://user-images.githubusercontent.com/90307689/154005382-e2f96131-751f-40c4-ae4c-5f147ffc1c55.png)

![hb-me](https://user-images.githubusercontent.com/90307689/154005394-5344ef03-fc2a-4ddf-a9e3-c40f69ed05f7.png)

**Comment by platypii** [comment] 2022-02-17 03:58
@t1u1 you are good at finding counter examples :-)

I just updated my earcut branch again to fix your example. I had to write a function to generate a polygon hierarchy, associating holes with their outer polygons. It seems like this is really close to working!

**Comment by t1u1** [comment] 2022-02-17 04:02
@platypii :) Wow, freak coincidence. I was just about to post simpler counter examples. Will try with your updates now!

**Comment by t1u1** [comment] 2022-02-17 04:07
@platypii I think you have hit gold. The happy birthday examples + the other examples I had in queue are working fine on your latest branch! Thanks! :heart: 

Could you publish a test or snapshot version to npm? I can then test it with my webapp.

**Comment by platypii** [comment] 2022-02-17 04:23
I'm not really sure how to publish it as a snapshot. I don't have access to the jscad account or anything. Maybe could generate a bundle file?

I plan to make a pull request after some cleanup.

**Comment by t1u1** [comment] 2022-02-17 04:25
Ok, sounds good. Will wait for the powers-that-be to make a release!

For regression testing, etc, here's a script that replicates all the examples so far:
https://gist.github.com/t1u1/6c6a4664b08ff6d4a9e9c6f3a87e7d31

(Note that some of the glitches were only evident in intermediate commits, but not in the current master, nor in the final earcut branch)

**Comment by hrgdavor** [comment] 2022-02-17 09:03
> I had to write a function to generate a polygon hierarchy, associating holes with their outer polygons. It seems like this is really close to working!

that is interesting, and now that you mentioned it makes perfect sense that it is needed.
Having tools that fixes stuff like this is excellent and should be part of the API.

From the performance perspective, extrude and other steps should not always run all possible fixing utilities.

If we want to be nice to new devs, fixing could be by default turned on, but we need for advanced users to be able to say: "I have proper polygons, no need to run fixes, and be faster".

**Comment by t1u1** [comment] 2022-02-27 04:29
> I plan to make a pull request after some cleanup.

Just a gentle reminder. Thanks for all the other PRs too!

**Comment by platypii** [comment] 2022-02-27 19:45
I have not forgotten. I'm doing some additional testing and tweaks to the Earcut implementation. The other PRs I made are small bugfixes -- for comparison, the earcut branch has over 1000 lines of new code, so I want to be careful. But it will be worth the wait! Some stats I posted on discord:

> With the latest optimization pass, my earcut branch is now significantly faster than master, and also more correct. It produces airtight geometry in less time!
> 
> Extruding a 50k circle on master: 18s
> Extruding a 50k circle on earcut: 0.5s

**Closed** 2022-03-12 02:20 UTC
Labels: BUG
